DROP DATABASE IF EXISTS examen;

CREATE DATABASE examen character set UTF8mb4 collate utf8mb4_bin;

USE examen;

CREATE TABLE refranero (
	id int(11) AUTO_INCREMENT PRIMARY KEY,
	sentence varchar (200) NOT NULL
);

INSERT INTO refranero (sentence) VALUES ("A barriga llena, corazon contento");
INSERT INTO refranero (sentence) VALUES ("A buen entendedor, pocas palabras bastan");
INSERT INTO refranero (sentence) VALUES ("A buen hambre, no hay pan duro");
INSERT INTO refranero (sentence) VALUES ("¡A buenas horas, mangas verdes!");
INSERT INTO refranero (sentence) VALUES ("A burro muerto, la cebada al rabo");
INSERT INTO refranero (sentence) VALUES ("A caballo regalado no le mires el diente");
INSERT INTO refranero (sentence) VALUES ("A cada cerdo le llega su San Martin");
INSERT INTO refranero (sentence) VALUES ("A Dios rogando y con el mazo dando");
INSERT INTO refranero (sentence) VALUES ("A enemigo que huye, puente de plata");
INSERT INTO refranero (sentence) VALUES ("A falta de pan, buenas son tortas");
INSERT INTO refranero (sentence) VALUES ("A grandes males, grandes remedios");
INSERT INTO refranero (sentence) VALUES ("A gusto de los cocineros comen los frailes");
INSERT INTO refranero (sentence) VALUES ("A la arrogancia en el pedir, la virtud del no dar");
INSERT INTO refranero (sentence) VALUES ("A la cama no te iras sin saber una cosa mas");
INSERT INTO refranero (sentence) VALUES ("A la tercera va la vencida");
INSERT INTO refranero (sentence) VALUES ("A la vejez, viruelas");
INSERT INTO refranero (sentence) VALUES ("A lo hecho, pecho");
INSERT INTO refranero (sentence) VALUES ("A mal tiempo, buena cara");
INSERT INTO refranero (sentence) VALUES ("A mas anos, mas desenganos");
INSERT INTO refranero (sentence) VALUES ("A nadie le amarga un dulce");
INSERT INTO refranero (sentence) VALUES ("A otro perro con ese hueso");
INSERT INTO refranero (sentence) VALUES ("A palabras necias, oidos sordos");
INSERT INTO refranero (sentence) VALUES ("A perro flaco, todo son pulgas");
INSERT INTO refranero (sentence) VALUES ("A quien cuece y amasa, de todo le pasa");
INSERT INTO refranero (sentence) VALUES ("A quien madruga, Dios le ayuda");
INSERT INTO refranero (sentence) VALUES ("A quien mucho tiene, mas le viene");
INSERT INTO refranero (sentence) VALUES ("A rey muerto, rey puesto");
INSERT INTO refranero (sentence) VALUES ("A rio revuelto, ganancia de pescadores");
INSERT INTO refranero (sentence) VALUES ("A todo se acostumbra uno, menos a no comer");
INSERT INTO refranero (sentence) VALUES ("A un clavo ardiendo se agarra el que se esta hundiendo");
INSERT INTO refranero (sentence) VALUES ("Abril, aguas mil");
INSERT INTO refranero (sentence) VALUES ("Afortunado en el juego, desafortunado en amores");
INSERT INTO refranero (sentence) VALUES ("Agua pasada no mueve molino");
INSERT INTO refranero (sentence) VALUES ("Agua que no has de beber dejala correr");
INSERT INTO refranero (sentence) VALUES ("Ahora adulador, manana traidor");
INSERT INTO refranero (sentence) VALUES ("Al mejor cazador, se le va la liebre");
INSERT INTO refranero (sentence) VALUES ("Al pan, pan, y al vino, vino");
INSERT INTO refranero (sentence) VALUES ("Al perro flaco, todo se le vuelven pulgas");
INSERT INTO refranero (sentence) VALUES ("Al que Dios se la de, San Pedro se la bendiga");
INSERT INTO refranero (sentence) VALUES ("Al que le pique, que se rasque");
INSERT INTO refranero (sentence) VALUES ("Al reves te lo digo para que me entiendas");
INSERT INTO refranero (sentence) VALUES ("Algo tendra el agua cuando la bendicen");
INSERT INTO refranero (sentence) VALUES ("Amigo por interes no dura porque no lo es");
INSERT INTO refranero (sentence) VALUES ("Amor con amor se paga");
INSERT INTO refranero (sentence) VALUES ("Amores renidos son los mas queridos");
INSERT INTO refranero (sentence) VALUES ("Ande yo caliente y riase la gente");
INSERT INTO refranero (sentence) VALUES ("Ante la duda, la mas tetuda");
INSERT INTO refranero (sentence) VALUES ("Antes de hacer nada, consultalo con la almohada");
INSERT INTO refranero (sentence) VALUES ("Antes de meter, prometer");
INSERT INTO refranero (sentence) VALUES ("Antes se coge al mentiroso que al cojo");
INSERT INTO refranero (sentence) VALUES ("Ano de nieves, ano de bienes");
INSERT INTO refranero (sentence) VALUES ("Aprendiz de mucho, maestro de nada");
INSERT INTO refranero (sentence) VALUES ("Arrieros somos, y en el camino nos encontraremos");
INSERT INTO refranero (sentence) VALUES ("Asno con oro, alcanzalo todo");
INSERT INTO refranero (sentence) VALUES ("Aunque la mona se vista de seda; mona se queda");
INSERT INTO refranero (sentence) VALUES ("Ave que vuela, a la cazuela");
INSERT INTO refranero (sentence) VALUES ("Bicho malo nunca muere");
INSERT INTO refranero (sentence) VALUES ("Bien esta lo que bien acaba");
INSERT INTO refranero (sentence) VALUES ("Bien predica quien bien vive");
INSERT INTO refranero (sentence) VALUES ("Buey viejo, surco derecho");
INSERT INTO refranero (sentence) VALUES ("Caballo grande, ande o no ande");
INSERT INTO refranero (sentence) VALUES ("Cada cosa a su tiempo");
INSERT INTO refranero (sentence) VALUES ("Cada loco con su tema");
INSERT INTO refranero (sentence) VALUES ("Cada maestrillo tiene su librillo");
INSERT INTO refranero (sentence) VALUES ("Cada mochuelo a su olivo");
INSERT INTO refranero (sentence) VALUES ("Cada moneda tiene dos caras");
INSERT INTO refranero (sentence) VALUES ("Cada oveja con su pareja");
INSERT INTO refranero (sentence) VALUES ("Cada palo aguante su vela");
INSERT INTO refranero (sentence) VALUES ("Cada persona es duena de su silencio y esclava de sus palabras");
INSERT INTO refranero (sentence) VALUES ("Cada uno cuenta de la feria como le va en ella");
INSERT INTO refranero (sentence) VALUES ("Cada uno en su casa, y Dios en la de todos");
INSERT INTO refranero (sentence) VALUES ("Cada uno lleva su cruz");
INSERT INTO refranero (sentence) VALUES ("Cada uno sabe donde le aprieta el zapato");
INSERT INTO refranero (sentence) VALUES ("Cada uno se conoce por sus obras");
INSERT INTO refranero (sentence) VALUES ("Cada uno tiene lo que se merece");
INSERT INTO refranero (sentence) VALUES ("Calumnia, que algo queda");
INSERT INTO refranero (sentence) VALUES ("Casa con dos puertas, mala es de guardar");
INSERT INTO refranero (sentence) VALUES ("Casaras y amansaras");
INSERT INTO refranero (sentence) VALUES ("Como eramos pocos, pario la abuela");
INSERT INTO refranero (sentence) VALUES ("Como se vive, se muere");
INSERT INTO refranero (sentence) VALUES ("Como siembres, recogeras");
INSERT INTO refranero (sentence) VALUES ("Con el roce, nace el carino");
INSERT INTO refranero (sentence) VALUES ("Con la ayuda del vecino, mato mi padre un cochino");
INSERT INTO refranero (sentence) VALUES ("Con la intencion basta");
INSERT INTO refranero (sentence) VALUES ("Con la verdad se llega a todas partes");
INSERT INTO refranero (sentence) VALUES ("Con las glorias se olvidan las memorias");
INSERT INTO refranero (sentence) VALUES ("Con pan y vino, se anda el camino");
INSERT INTO refranero (sentence) VALUES ("Consejos vendo, y para mi no tengo");
INSERT INTO refranero (sentence) VALUES ("Contigo, pan y cebolla");
INSERT INTO refranero (sentence) VALUES ("Contra el vicio de pedir, la virtud de no dar");
INSERT INTO refranero (sentence) VALUES ("Contra la fortuna, no hay arte alguna");
INSERT INTO refranero (sentence) VALUES ("Corazon codicioso, no tiene reposo");
INSERT INTO refranero (sentence) VALUES ("Coser y cantar, todo es empezar");
INSERT INTO refranero (sentence) VALUES ("Cree el ladron que todos son de su condicion");
INSERT INTO refranero (sentence) VALUES ("Cria fama y echate a dormir");
INSERT INTO refranero (sentence) VALUES ("Cria cuervos y te sacaran los ojos");
INSERT INTO refranero (sentence) VALUES ("Cuando el diablo no tiene nada que hacer, mata moscas con el rabo");
INSERT INTO refranero (sentence) VALUES ("Cuando el gato no esta, los ratones bailan");
INSERT INTO refranero (sentence) VALUES ("Cuando el grajo vuela bajo, hace un frio del carajo");
INSERT INTO refranero (sentence) VALUES ("Cuando el rio suena, agua lleva");
INSERT INTO refranero (sentence) VALUES ("Cuando las barbas del vecino veas pelar, pon las tuyas a remojar");
INSERT INTO refranero (sentence) VALUES ("Cuando menos se piensa, salta la liebre");
INSERT INTO refranero (sentence) VALUES ("Cuando una puerta se cierra, otra se abre");
INSERT INTO refranero (sentence) VALUES ("Cuanto mas se tiene, mas se quiere");
INSERT INTO refranero (sentence) VALUES ("Cuanto mas viejo, mas pellejo");
INSERT INTO refranero (sentence) VALUES ("Cuidados ajenos mataron al asno");
INSERT INTO refranero (sentence) VALUES ("Culo veo, culo deseo");
INSERT INTO refranero (sentence) VALUES ("Da Dios almendras al que no tiene muelas");
INSERT INTO refranero (sentence) VALUES ("Dame pan, y dime tonto");
INSERT INTO refranero (sentence) VALUES ("Date prisa despacio, y llegaras a palacio");
INSERT INTO refranero (sentence) VALUES ("De aquellos polvos, vienen estos lodos");
INSERT INTO refranero (sentence) VALUES ("De buen vino, buen vinagre");
INSERT INTO refranero (sentence) VALUES ("De casta le viene al galgo el ser rabilargo");
INSERT INTO refranero (sentence) VALUES ("De desagradecidos esta el infierno lleno");
INSERT INTO refranero (sentence) VALUES ("De donde no hay, no se puede sacar");
INSERT INTO refranero (sentence) VALUES ("De la calle vendra, quien de tu casa te echara");
INSERT INTO refranero (sentence) VALUES ("De grandes cenas estan las sepulturas llenas");
INSERT INTO refranero (sentence) VALUES ("De herrero a herrero, no pasa dinero");
INSERT INTO refranero (sentence) VALUES ("De ilusion tambien se vive");
INSERT INTO refranero (sentence) VALUES ("De la discusion nace la luz");
INSERT INTO refranero (sentence) VALUES ("De lo que no cuesta, llena la cesta");
INSERT INTO refranero (sentence) VALUES ("De lo que no veas, ni la mitad te creas");
INSERT INTO refranero (sentence) VALUES ("De lo que se come se cria");
INSERT INTO refranero (sentence) VALUES ("De los amigos me guarde Dios, que de los enemigos me guardo yo");
INSERT INTO refranero (sentence) VALUES ("De los cuarenta para arriba, no te mojes la barriga");
INSERT INTO refranero (sentence) VALUES ("De los escarmentados nacen los avisados");
INSERT INTO refranero (sentence) VALUES ("De mi te reiras, pero de mi dinero, no");
INSERT INTO refranero (sentence) VALUES ("De noche todos los gatos son pardos");
INSERT INTO refranero (sentence) VALUES ("De perdidos, al rio");
INSERT INTO refranero (sentence) VALUES ("De tal cepa, tal vino");
INSERT INTO refranero (sentence) VALUES ("De tal palo, tal astilla");
INSERT INTO refranero (sentence) VALUES ("De todo hay en la vina del Senor");
INSERT INTO refranero (sentence) VALUES ("De trigo y avena, mi casa llena");
INSERT INTO refranero (sentence) VALUES ("De una cebolla no nace una rosa");
INSERT INTO refranero (sentence) VALUES ("Del agua mansa libreme Dios, que de la brava me librare yo");
INSERT INTO refranero (sentence) VALUES ("Del amor al odio hay un paso");
INSERT INTO refranero (sentence) VALUES ("Del arbol caido, todos hacen lena");
INSERT INTO refranero (sentence) VALUES ("Del dicho al hecho hay un buen trecho");
INSERT INTO refranero (sentence) VALUES ("Del jefe y del mulo cuanto mas lejos mas seguro");
INSERT INTO refranero (sentence) VALUES ("Del mar, el mero; de la tierra, el cordero");
INSERT INTO refranero (sentence) VALUES ("Del viejo, el consejo");
INSERT INTO refranero (sentence) VALUES ("Dentro de cien anos, todos calvos");
INSERT INTO refranero (sentence) VALUES ("Desdichas y caminos hacen amigos");
INSERT INTO refranero (sentence) VALUES ("Desgracia compartida, menos sentida");
INSERT INTO refranero (sentence) VALUES ("Desgraciado en el juego, afortunado en amores");
INSERT INTO refranero (sentence) VALUES ("Desnudar un santo para vestir otro");
INSERT INTO refranero (sentence) VALUES ("Desnudo naci, desnudo me hallo: ni pierdo ni gano");
INSERT INTO refranero (sentence) VALUES ("Despues de beber, cada uno dice su parecer");
INSERT INTO refranero (sentence) VALUES ("Despues de la tempestad, viene la calma");
INSERT INTO refranero (sentence) VALUES ("Detras de la cruz esta el diablo");
INSERT INTO refranero (sentence) VALUES ("Dia de Santa Lucia, mengua la noche y crece el dia");
INSERT INTO refranero (sentence) VALUES ("Dias de mucho, visperas de nada");
INSERT INTO refranero (sentence) VALUES ("Dicho y hecho");
INSERT INTO refranero (sentence) VALUES ("Diciendo las verdades se pierden amistades");
INSERT INTO refranero (sentence) VALUES ("Dime con quien andas y te dire quien eres");
INSERT INTO refranero (sentence) VALUES ("Dime de que presumes y te dire de que careces");
INSERT INTO refranero (sentence) VALUES ("Dinero llama dinero");
INSERT INTO refranero (sentence) VALUES ("Dios aprieta pero no ahoga");
INSERT INTO refranero (sentence) VALUES ("Dios los cria y ellos se juntan");
INSERT INTO refranero (sentence) VALUES ("Divide y venceras");
INSERT INTO refranero (sentence) VALUES ("Donde dije digo, digo Diego");
INSERT INTO refranero (sentence) VALUES ("Donde fueres, haz lo que vieres");
INSERT INTO refranero (sentence) VALUES ("Donde hay confianza, da asco");
INSERT INTO refranero (sentence) VALUES ("Donde hay patron, no manda marinero");
INSERT INTO refranero (sentence) VALUES ("Donde las dan las toman");
INSERT INTO refranero (sentence) VALUES ("Donde manda el corazon, la cabeza tiene poco que decir");
INSERT INTO refranero (sentence) VALUES ("Donde menos se piensa salta la liebre");
INSERT INTO refranero (sentence) VALUES ("¿Donde va Vicente?, donde va la gente");
INSERT INTO refranero (sentence) VALUES ("Dos es compania, tres es multitud");
INSERT INTO refranero (sentence) VALUES ("Dos no rinen, si uno no quiere");
INSERT INTO refranero (sentence) VALUES ("Dos que duermen en un colchon, se vuelven de la misma condicion");
INSERT INTO refranero (sentence) VALUES ("El amor es ciego");
INSERT INTO refranero (sentence) VALUES ("El avaro, cuanto mas tiene, mas quiere");
INSERT INTO refranero (sentence) VALUES ("El bien viene andando; el mal, volando");
INSERT INTO refranero (sentence) VALUES ("El buen cirujano corta por lo sano");
INSERT INTO refranero (sentence) VALUES ("El buen pano en el arca se vende");
INSERT INTO refranero (sentence) VALUES ("El buen perfume se vende en frasco pequeno");
INSERT INTO refranero (sentence) VALUES ("El buey suelto, bien se lame");
INSERT INTO refranero (sentence) VALUES ("El casado, casa quiere");
INSERT INTO refranero (sentence) VALUES ("El comer y el rascar, todo es empezar");
INSERT INTO refranero (sentence) VALUES ("El dinero hace caballero");
INSERT INTO refranero (sentence) VALUES ("El fin justifica los medios");
INSERT INTO refranero (sentence) VALUES ("El fruto prohibido es el mas apetecido");
INSERT INTO refranero (sentence) VALUES ("El gato escaldado, del agua fria huye");
INSERT INTO refranero (sentence) VALUES ("El habito no hace al monje");
INSERT INTO refranero (sentence) VALUES ("El hambre aguza el ingenio");
INSERT INTO refranero (sentence) VALUES ("El hambre es muy mala consejera");
INSERT INTO refranero (sentence) VALUES ("El hombre es el unico animal que tropieza dos veces en la misma piedra");
INSERT INTO refranero (sentence) VALUES ("El hombre propone, y Dios dispone");
INSERT INTO refranero (sentence) VALUES ("El hombre y el oso, cuanto mas feo, mas hermoso");
INSERT INTO refranero (sentence) VALUES ("El huesped y el pez, a los tres dias hiede");
INSERT INTO refranero (sentence) VALUES ("El invierno no es pasado mientras abril no es terminado");
INSERT INTO refranero (sentence) VALUES ("El llanto, sobre el difunto");
INSERT INTO refranero (sentence) VALUES ("El lloro de la mujer, no es de creer");
INSERT INTO refranero (sentence) VALUES ("El mejor escribano echa un borron");
INSERT INTO refranero (sentence) VALUES ("El mentiroso ha de ser memorioso");
INSERT INTO refranero (sentence) VALUES ("El muerto al hoyo y el vivo al bollo");
INSERT INTO refranero (sentence) VALUES ("El mundo es un panuelo");
INSERT INTO refranero (sentence) VALUES ("El ocio no quede impune; quien no trabaje, que ayune");
INSERT INTO refranero (sentence) VALUES ("El ojo del amo engorda el caballo");
INSERT INTO refranero (sentence) VALUES ("El perro del hortelano, ni come ni deja comer al amo");
INSERT INTO refranero (sentence) VALUES ("El pez grande se come al chico");
INSERT INTO refranero (sentence) VALUES ("El poeta nace, no se hace");
INSERT INTO refranero (sentence) VALUES ("El que a buen arbol se arrima, buena sombra le cobija");
INSERT INTO refranero (sentence) VALUES ("El que a hierro mata, a hierro muere");
INSERT INTO refranero (sentence) VALUES ("El que al cielo escupe en la cara le cae");
INSERT INTO refranero (sentence) VALUES ("El que algo quiere, algo le cuesta");
INSERT INTO refranero (sentence) VALUES ("El que avisa no es traidor");
INSERT INTO refranero (sentence) VALUES ("El que busca halla");
INSERT INTO refranero (sentence) VALUES ("El que calla, otorga");
INSERT INTO refranero (sentence) VALUES ("El que espera, desespera");
INSERT INTO refranero (sentence) VALUES ("El que este libre de pecado, que tire la primera piedra");
INSERT INTO refranero (sentence) VALUES ("El que fue a Sevilla perdio su silla");
INSERT INTO refranero (sentence) VALUES ("El que guarda, siempre tiene");
INSERT INTO refranero (sentence) VALUES ("El que la sigue, la consigue");
INSERT INTO refranero (sentence) VALUES ("El que mucho corre, pronto para");
INSERT INTO refranero (sentence) VALUES ("El que mucho habla, mucho yerra");
INSERT INTO refranero (sentence) VALUES ("El que mucho ofrece, poco da");
INSERT INTO refranero (sentence) VALUES ("El que no llora, no mama");
INSERT INTO refranero (sentence) VALUES ("El que no quiera polvo, que no vaya a la era");
INSERT INTO refranero (sentence) VALUES ("El que no se consuela, es porque no quiere");
INSERT INTO refranero (sentence) VALUES ("El que no trabaja, no come");
INSERT INTO refranero (sentence) VALUES ("El que parte y reparte, se queda con la mejor parte");
INSERT INTO refranero (sentence) VALUES ("El que pega primero, pega dos veces");
INSERT INTO refranero (sentence) VALUES ("El que quiera peces que se moje el culo");
INSERT INTO refranero (sentence) VALUES ("El que rie el ultimo, rie mejor");
INSERT INTO refranero (sentence) VALUES ("El que rompe, paga");
INSERT INTO refranero (sentence) VALUES ("El que se excusa, se acusa");
INSERT INTO refranero (sentence) VALUES ("El que se pica, ajos come");
INSERT INTO refranero (sentence) VALUES ("El que siembra viento, cosecha tempestades");
INSERT INTO refranero (sentence) VALUES ("El que tiene boca, se equivoca");
INSERT INTO refranero (sentence) VALUES ("El que tiene padrino se bautiza");
INSERT INTO refranero (sentence) VALUES ("El que tiene un tio en Alcala, ni tiene tio ni tiene na");
INSERT INTO refranero (sentence) VALUES ("El que tuvo, retuvo");
INSERT INTO refranero (sentence) VALUES ("El que venga detras, que arree");
INSERT INTO refranero (sentence) VALUES ("El que vive de favores, sirve a muchos senores");
INSERT INTO refranero (sentence) VALUES ("El saber no ocupa lugar");
INSERT INTO refranero (sentence) VALUES ("El sabio siempre quiere aprender, el ignorante siempre quiere ensenar");
INSERT INTO refranero (sentence) VALUES ("El tiempo es oro");
INSERT INTO refranero (sentence) VALUES ("El tiempo lo dira");
INSERT INTO refranero (sentence) VALUES ("El tiempo perdido no se recupera");
INSERT INTO refranero (sentence) VALUES ("El tiempo pone a cada uno en su sitio");
INSERT INTO refranero (sentence) VALUES ("El tiempo todo lo cura");
INSERT INTO refranero (sentence) VALUES ("En boca cerrada no entran moscas");
INSERT INTO refranero (sentence) VALUES ("En casa del herrero, cuchillo de palo");
INSERT INTO refranero (sentence) VALUES ("En casa del pobre, dura poco la alegria");
INSERT INTO refranero (sentence) VALUES ("En el pais de los ciegos, el tuerto es el rey");
INSERT INTO refranero (sentence) VALUES ("En febrero busca la sombra el perro");
INSERT INTO refranero (sentence) VALUES ("En la guerra y en el amor, todo vale");
INSERT INTO refranero (sentence) VALUES ("En la tardanza esta el peligro");
INSERT INTO refranero (sentence) VALUES ("En la variedad esta el gusto");
INSERT INTO refranero (sentence) VALUES ("En martes, ni te cases ni te embarques");
INSERT INTO refranero (sentence) VALUES ("En tiempo de higos no hay amigos");
INSERT INTO refranero (sentence) VALUES ("En todas partes cuecen habas");
INSERT INTO refranero (sentence) VALUES ("Encender una vela a Dios y otra al diablo");
INSERT INTO refranero (sentence) VALUES ("Entre col y col, lechuga");
INSERT INTO refranero (sentence) VALUES ("Entre dos amigos, un notario y dos testigos");
INSERT INTO refranero (sentence) VALUES ("Entre todos la mataron y ella sola se murio");
INSERT INTO refranero (sentence) VALUES ("Es buena noticia el que no las haya");
INSERT INTO refranero (sentence) VALUES ("Es de bien nacidos ser agradecidos");
INSERT INTO refranero (sentence) VALUES ("Es la gota que desborda el vaso");
INSERT INTO refranero (sentence) VALUES ("Es peor el remedio que la enfermedad");
INSERT INTO refranero (sentence) VALUES ("Escoba nueva barre bien");
INSERT INTO refranero (sentence) VALUES ("Gallina vieja hace buen caldo");
INSERT INTO refranero (sentence) VALUES ("Gallo que no canta, algo tiene en la garganta");
INSERT INTO refranero (sentence) VALUES ("Gato con guantes no caza ratones");
INSERT INTO refranero (sentence) VALUES ("Gato escaldado, del agua fria huye");
INSERT INTO refranero (sentence) VALUES ("Genio y figura, hasta la sepultura");
INSERT INTO refranero (sentence) VALUES ("Gota a gota, se llena la bota");
INSERT INTO refranero (sentence) VALUES ("Gusta lo ajeno mas por ajeno que por bueno");
INSERT INTO refranero (sentence) VALUES ("Hablando del rey de Roma, por la puerta asoma");
INSERT INTO refranero (sentence) VALUES ("Hablando se entiende la gente");
INSERT INTO refranero (sentence) VALUES ("Hablo el buey y dijo mu");
INSERT INTO refranero (sentence) VALUES ("Haciendo y deshaciendo se va aprendiendo");
INSERT INTO refranero (sentence) VALUES ("Hambre que espera hartura, no es hambre pura");
INSERT INTO refranero (sentence) VALUES ("Hasta el cuarenta de mayo no te quites el sayo");
INSERT INTO refranero (sentence) VALUES ("Hasta el rabo, todo es toro");
INSERT INTO refranero (sentence) VALUES ("Hay mas dias que longanizas");
INSERT INTO refranero (sentence) VALUES ("Haz bien y no mires a quien");
INSERT INTO refranero (sentence) VALUES ("Hijo sin dolor, madre sin amor");
INSERT INTO refranero (sentence) VALUES ("Hombre prevenido, vale por dos");
INSERT INTO refranero (sentence) VALUES ("Hoy por ti, manana por mi");
INSERT INTO refranero (sentence) VALUES ("Huir del fuego para caer en las brasas");
INSERT INTO refranero (sentence) VALUES ("Ir por lana y volver trasquilado");
INSERT INTO refranero (sentence) VALUES ("Jaula nueva, pajaro muerto");
INSERT INTO refranero (sentence) VALUES ("Juan Palomo, yo me lo guiso y yo me lo como");
INSERT INTO refranero (sentence) VALUES ("Juego y bebida, casa perdida");
INSERT INTO refranero (sentence) VALUES ("La arruga es bella");
INSERT INTO refranero (sentence) VALUES ("La ausencia causa olvido");
INSERT INTO refranero (sentence) VALUES ("La avaricia rompe el saco");
INSERT INTO refranero (sentence) VALUES ("La cabra siempre tira al monte");
INSERT INTO refranero (sentence) VALUES ("La cara es el espejo del alma");
INSERT INTO refranero (sentence) VALUES ("La caridad bien entendida empieza por uno mismo");
INSERT INTO refranero (sentence) VALUES ("La casa se arruina por la cocina");
INSERT INTO refranero (sentence) VALUES ("La costumbre hace ley");
INSERT INTO refranero (sentence) VALUES ("La curiosidad mato al gato");
INSERT INTO refranero (sentence) VALUES ("La ensalada, poco vinagre y bien aceitada");
INSERT INTO refranero (sentence) VALUES ("La esperanza es lo ultimo que se pierde");
INSERT INTO refranero (sentence) VALUES ("La excepcion confirma la regla");
INSERT INTO refranero (sentence) VALUES ("La experiencia es la madre de la ciencia");
INSERT INTO refranero (sentence) VALUES ("La fe mueve montanas");
INSERT INTO refranero (sentence) VALUES ("La gallina de mi vecina mas huevos pone que la mia");
INSERT INTO refranero (sentence) VALUES ("La hermosura poco dura");
INSERT INTO refranero (sentence) VALUES ("La ignorancia de la ley no excusa su cumplimiento");
INSERT INTO refranero (sentence) VALUES ("La intencion es lo que vale");
INSERT INTO refranero (sentence) VALUES ("La juventud tiene la fuerza y la vejez la prudencia");
INSERT INTO refranero (sentence) VALUES ("La lengua no tiene hueso, pero corta lo mas grueso");
INSERT INTO refranero (sentence) VALUES ("La letra con sangre entra");
INSERT INTO refranero (sentence) VALUES ("La ley del embudo, para mi lo ancho y para ti lo agudo");
INSERT INTO refranero (sentence) VALUES ("La manzana podrida pierde a su compania");
INSERT INTO refranero (sentence) VALUES ("La mejor palabra siempre es la que queda por decir");
INSERT INTO refranero (sentence) VALUES ("La mejor salsa, el apetito");
INSERT INTO refranero (sentence) VALUES ("La mujer del Cesar, ademas de ser honesta, debe parecerlo");
INSERT INTO refranero (sentence) VALUES ("La mujer y el oro, lo pueden todo");
INSERT INTO refranero (sentence) VALUES ("La mujer y el vino sacan al hombre de tino");
INSERT INTO refranero (sentence) VALUES ("La musica amansa las fieras");
INSERT INTO refranero (sentence) VALUES ("La ocasion la pintan calva");
INSERT INTO refranero (sentence) VALUES ("La palabra es plata y el silencio es oro");
INSERT INTO refranero (sentence) VALUES ("La palabra que sale de la boca, nunca torna");
INSERT INTO refranero (sentence) VALUES ("La peor gallina es la que mas cacarea");
INSERT INTO refranero (sentence) VALUES ("La perseverancia todo lo alcanza");
INSERT INTO refranero (sentence) VALUES ("La primavera la sangre altera");
INSERT INTO refranero (sentence) VALUES ("La procesion va por dentro");
INSERT INTO refranero (sentence) VALUES ("La realidad supera la ficcion");
INSERT INTO refranero (sentence) VALUES ("La respuesta mansa la ira quebranta");
INSERT INTO refranero (sentence) VALUES ("La suegra y el doctor, cuanto mas lejos, mejor");
INSERT INTO refranero (sentence) VALUES ("La suerte de la fea, la bonita la desea");
INSERT INTO refranero (sentence) VALUES ("La suerte esta echada");
INSERT INTO refranero (sentence) VALUES ("La union hace la fuerza");
INSERT INTO refranero (sentence) VALUES ("La venganza es un plato que se sirve frio");
INSERT INTO refranero (sentence) VALUES ("La verdad es amarga");
INSERT INTO refranero (sentence) VALUES ("La vida no es un camino de rosas");
INSERT INTO refranero (sentence) VALUES ("La viuda rica hace que llora y repica");
INSERT INTO refranero (sentence) VALUES ("Las apariencias enganan");
INSERT INTO refranero (sentence) VALUES ("Las armas de fuego, cuanto mas lejos, mejor");
INSERT INTO refranero (sentence) VALUES ("Las comparaciones son odiosas");
INSERT INTO refranero (sentence) VALUES ("Las cosas de palacio van despacio");
INSERT INTO refranero (sentence) VALUES ("Las cuentas claras, y el chocolate espeso");
INSERT INTO refranero (sentence) VALUES ("Las desgracias nunca vienen solas");
INSERT INTO refranero (sentence) VALUES ("Las madres hacendosas hacen las hijas perezosas");
INSERT INTO refranero (sentence) VALUES ("Las malas noticias vuelan");
INSERT INTO refranero (sentence) VALUES ("Las palabras vuelan, y lo escrito permanece");
INSERT INTO refranero (sentence) VALUES ("Las paredes oyen");
INSERT INTO refranero (sentence) VALUES ("Las prisas nunca son buenas");
INSERT INTO refranero (sentence) VALUES ("Libro prestado, libro perdido");
INSERT INTO refranero (sentence) VALUES ("Lo barato sale caro");
INSERT INTO refranero (sentence) VALUES ("Lo bien hecho, bien parece");
INSERT INTO refranero (sentence) VALUES ("Lo bueno poco dura");
INSERT INTO refranero (sentence) VALUES ("Lo bueno, si breve, dos veces bueno");
INSERT INTO refranero (sentence) VALUES ("Lo comido por lo servido");
INSERT INTO refranero (sentence) VALUES ("Lo cortes no quita lo valiente");
INSERT INTO refranero (sentence) VALUES ("Lo fiado, rara vez pagado");
INSERT INTO refranero (sentence) VALUES ("Lo olvidado, ni agradecido ni pagado");
INSERT INTO refranero (sentence) VALUES ("Lo prometido es deuda");
INSERT INTO refranero (sentence) VALUES ("Lo que a unos mata, a otros sana");
INSERT INTO refranero (sentence) VALUES ("Lo que bien empieza, bien acaba");
INSERT INTO refranero (sentence) VALUES ("Lo que de noche se hace, a la manana parece");
INSERT INTO refranero (sentence) VALUES ("Lo que en los libros no esta, la vida te lo ensenara");
INSERT INTO refranero (sentence) VALUES ("Lo que es moda no incomoda");
INSERT INTO refranero (sentence) VALUES ("Lo que mucho vale, mucho cuesta");
INSERT INTO refranero (sentence) VALUES ("Lo que no has de comer, dejalo cocer");
INSERT INTO refranero (sentence) VALUES ("Lo que no mata, engorda");
INSERT INTO refranero (sentence) VALUES ("Lo que no se comienza, nunca se acaba");
INSERT INTO refranero (sentence) VALUES ("Lo que no se llevan los ladrones, aparece por los rincones");
INSERT INTO refranero (sentence) VALUES ("Lo que no va en lagrimas va en suspiros");
INSERT INTO refranero (sentence) VALUES ("Lo que otro suda, a mi poco me dura");
INSERT INTO refranero (sentence) VALUES ("Lo que poco cuesta, poco se aprecia");
INSERT INTO refranero (sentence) VALUES ("Lo que se aprende en la cuna, siempre dura");
INSERT INTO refranero (sentence) VALUES ("Lo que sea sonara");
INSERT INTO refranero (sentence) VALUES ("Los amigos de mis amigos son mis amigos");
INSERT INTO refranero (sentence) VALUES ("Los amigos de mis amigos son mis amigos");
INSERT INTO refranero (sentence) VALUES ("Los anos no pasan en balde");
INSERT INTO refranero (sentence) VALUES ("Los arboles no dejan ver el bosque");
INSERT INTO refranero (sentence) VALUES ("Los celos son malos consejeros");
INSERT INTO refranero (sentence) VALUES ("Los duelos con pan, son menos");
INSERT INTO refranero (sentence) VALUES ("Los huespedes mucho gusto dan, pero cuando se van");
INSERT INTO refranero (sentence) VALUES ("Los malos tragos hay que pasarlos pronto");
INSERT INTO refranero (sentence) VALUES ("Los ninos y los locos dicen las verdades");
INSERT INTO refranero (sentence) VALUES ("Los toros se ven mejor desde la barrera");
INSERT INTO refranero (sentence) VALUES ("Los trapos sucios se lavan en casa");
INSERT INTO refranero (sentence) VALUES ("Mal de muchos, consuelo de tontos");
INSERT INTO refranero (sentence) VALUES ("Manana sera otro dia");
INSERT INTO refranero (sentence) VALUES ("Manitas que no dais, ¿que esperais?");
INSERT INTO refranero (sentence) VALUES ("Manos frias, corazon caliente");
INSERT INTO refranero (sentence) VALUES ("Marido celoso no tiene reposo");
INSERT INTO refranero (sentence) VALUES ("Marzo ventoso y abril lluvioso sacan a mayo florido y hermoso");
INSERT INTO refranero (sentence) VALUES ("Mas hace el que quiere que el que puede");
INSERT INTO refranero (sentence) VALUES ("Mas discurre un hambriento que cien letrados");
INSERT INTO refranero (sentence) VALUES ("Mas sabe el diablo por viejo que por diablo");
INSERT INTO refranero (sentence) VALUES ("Mas vale caer en gracia que ser gracioso");
INSERT INTO refranero (sentence) VALUES ("Mas vale estar solo que mal acompanado");
INSERT INTO refranero (sentence) VALUES ("Mas vale gastar en pan que en botica");
INSERT INTO refranero (sentence) VALUES ("Mas vale llegar a tiempo que rondar un ano");
INSERT INTO refranero (sentence) VALUES ("Mas vale malo conocido que lo bueno por conocer");
INSERT INTO refranero (sentence) VALUES ("Mas vale mana que fuerza");
INSERT INTO refranero (sentence) VALUES ("Mas vale pajaro en mano que ciento volando");
INSERT INTO refranero (sentence) VALUES ("Mas vale prevenir que curar");
INSERT INTO refranero (sentence) VALUES ("Mas vale ser arriero que borrico");
INSERT INTO refranero (sentence) VALUES ("Mas vale tarde que nunca");
INSERT INTO refranero (sentence) VALUES ("Mas vale tener que desear");
INSERT INTO refranero (sentence) VALUES ("Mas vale tuerto que ciego");
INSERT INTO refranero (sentence) VALUES ("Mas vale un mal arreglo que un buen pleito");
INSERT INTO refranero (sentence) VALUES ("Mas ven cuatro ojos que dos");
INSERT INTO refranero (sentence) VALUES ("Mejor dar que recibir");
INSERT INTO refranero (sentence) VALUES ("Mucho ruido y pocas nueces");
INSERT INTO refranero (sentence) VALUES ("Muchos son los llamados y pocos los escogidos");
INSERT INTO refranero (sentence) VALUES ("Muerto el perro, se acabo la rabia");
INSERT INTO refranero (sentence) VALUES ("Nadie da lo que no tiene");
INSERT INTO refranero (sentence) VALUES ("Nadie es profeta en su tierra");
INSERT INTO refranero (sentence) VALUES ("Nadie escarmienta en cabeza ajena");
INSERT INTO refranero (sentence) VALUES ("Nadie se acuerda de Santa Barbara hasta que truena");
INSERT INTO refranero (sentence) VALUES ("Nadie se meta donde no le llamen");
INSERT INTO refranero (sentence) VALUES ("Nadie tira piedras a su tejado");
INSERT INTO refranero (sentence) VALUES ("Ni pidas a quien pidio, ni sirvas a quien sirvio");
INSERT INTO refranero (sentence) VALUES ("Ni son todos los que estan, ni estan todos los que son");
INSERT INTO refranero (sentence) VALUES ("Ni tanto ni tan calvo");
INSERT INTO refranero (sentence) VALUES ("Ningun jorobado ve su joroba");
INSERT INTO refranero (sentence) VALUES ("Ninguno escarmienta en cabeza ajena");
INSERT INTO refranero (sentence) VALUES ("No basta ser bueno sino parecerlo");
INSERT INTO refranero (sentence) VALUES ("No cantan dos gallos en un gallinero");
INSERT INTO refranero (sentence) VALUES ("No cantes gloria hasta el fin de la victoria");
INSERT INTO refranero (sentence) VALUES ("No cojas la pera hasta que este madura");
INSERT INTO refranero (sentence) VALUES ("No comer por haber comido no es tiempo perdido");
INSERT INTO refranero (sentence) VALUES ("No con quien naces sino con quien paces");
INSERT INTO refranero (sentence) VALUES ("No dejes para manana lo que puedas hacer hoy");
INSERT INTO refranero (sentence) VALUES ("No echeis margaritas a los cerdos");
INSERT INTO refranero (sentence) VALUES ("No es lo mismo ser que parecer");
INSERT INTO refranero (sentence) VALUES ("No es mas limpio el que mas limpia, sino el que menos ensucia");
INSERT INTO refranero (sentence) VALUES ("No es mas rico quien mas tiene sino el que menos necesita");
INSERT INTO refranero (sentence) VALUES ("No es oro todo lo que reluce");
INSERT INTO refranero (sentence) VALUES ("No es tan fiero el leon como lo pintan");
INSERT INTO refranero (sentence) VALUES ("No hay don sin din");
INSERT INTO refranero (sentence) VALUES ("No hay enemigo pequeno");
INSERT INTO refranero (sentence) VALUES ("No hay harina sin salvado");
INSERT INTO refranero (sentence) VALUES ("No hay mal que cien anos dure");
INSERT INTO refranero (sentence) VALUES ("No hay mal que por bien no venga");
INSERT INTO refranero (sentence) VALUES ("No hay mayor desprecio que no hacer aprecio");
INSERT INTO refranero (sentence) VALUES ("No hay peor ciego que el que no quiere ver");
INSERT INTO refranero (sentence) VALUES ("No hay peor sordo que el que no quiere oir");
INSERT INTO refranero (sentence) VALUES ("No hay primavera sin flores ni verano sin calores");
INSERT INTO refranero (sentence) VALUES ("No hay que empezar la casa por el tejado");
INSERT INTO refranero (sentence) VALUES ("No hay que fiarse de las apariencias");
INSERT INTO refranero (sentence) VALUES ("No hay que vender la piel del oso antes de haberlo cazado");
INSERT INTO refranero (sentence) VALUES ("No hay regla sin excepcion");
INSERT INTO refranero (sentence) VALUES ("No hay rosa sin espinas");
INSERT INTO refranero (sentence) VALUES ("No hay tonto que no se tenga por listo");
INSERT INTO refranero (sentence) VALUES ("No muerdas la mano que te da de comer");
INSERT INTO refranero (sentence) VALUES ("No ofende quien quiere sino quien puede");
INSERT INTO refranero (sentence) VALUES ("No por mucho madrugar, amanece mas temprano");
INSERT INTO refranero (sentence) VALUES ("No quieres caldo, pues toma tres tazas");
INSERT INTO refranero (sentence) VALUES ("No sabes lo que tienes hasta que lo pierdes");
INSERT INTO refranero (sentence) VALUES ("No se acuerda el cura de cuando fue sacristan");
INSERT INTO refranero (sentence) VALUES ("No se gano Zamora en una hora");
INSERT INTO refranero (sentence) VALUES ("No se hizo la miel para la boca del asno");
INSERT INTO refranero (sentence) VALUES ("No se puede estar en misa y repicando");
INSERT INTO refranero (sentence) VALUES ("No se puede hacer tortilla sin romper los huevos");
INSERT INTO refranero (sentence) VALUES ("No solo de pan vive el hombre");
INSERT INTO refranero (sentence) VALUES ("No te cierres una puerta, si no has abierto otra");
INSERT INTO refranero (sentence) VALUES ("No te rias del mal de vecino, que el tuyo viene de camino");
INSERT INTO refranero (sentence) VALUES ("No tires piedras sobre tu tejado");
INSERT INTO refranero (sentence) VALUES ("No todo el monte es oregano");
INSERT INTO refranero (sentence) VALUES ("No vendas la piel de oso antes de haberlo cazado");
INSERT INTO refranero (sentence) VALUES ("Nuestro gozo en un pozo");
INSERT INTO refranero (sentence) VALUES ("Nunca digas de este agua no bebere");
INSERT INTO refranero (sentence) VALUES ("Nunca es tarde si la dicha es buena");
INSERT INTO refranero (sentence) VALUES ("Nunca falta un roto para un descosido");
INSERT INTO refranero (sentence) VALUES ("Nunca llueve a gusto de todos");
INSERT INTO refranero (sentence) VALUES ("Nunca segundas partes fueron buenas");
INSERT INTO refranero (sentence) VALUES ("Obras son amores, que no buenas razones");
INSERT INTO refranero (sentence) VALUES ("Ojo por ojo, diente por diente");
INSERT INTO refranero (sentence) VALUES ("Ojos que no ven, corazon que no siente");
INSERT INTO refranero (sentence) VALUES ("Otro vendra que bueno me hara");
INSERT INTO refranero (sentence) VALUES ("Oveja que bala, bocado que pierde");
INSERT INTO refranero (sentence) VALUES ("Palos con gusto no duelen");
INSERT INTO refranero (sentence) VALUES ("Pan con pan, comida de tontos");
INSERT INTO refranero (sentence) VALUES ("Pan para hoy, y hambre para manana");
INSERT INTO refranero (sentence) VALUES ("Para ese viaje no se necesitan alforjas");
INSERT INTO refranero (sentence) VALUES ("Para muestra, un boton");
INSERT INTO refranero (sentence) VALUES ("Paso a paso se va lejos");
INSERT INTO refranero (sentence) VALUES ("Pelillos a la mar");
INSERT INTO refranero (sentence) VALUES ("Perro ladrador, poco mordedor");
INSERT INTO refranero (sentence) VALUES ("Pesar ajeno, no quita el sueno");
INSERT INTO refranero (sentence) VALUES ("Piensa el ladron que todos son de su condicion");
INSERT INTO refranero (sentence) VALUES ("Piensa mal y acertaras");
INSERT INTO refranero (sentence) VALUES ("Pleitos tengas y los ganes");
INSERT INTO refranero (sentence) VALUES ("Poco a poco se llega antes");
INSERT INTO refranero (sentence) VALUES ("Pocos y mal avenidos");
INSERT INTO refranero (sentence) VALUES ("Poderoso caballero es don dinero");
INSERT INTO refranero (sentence) VALUES ("Por dinero baila el perro");
INSERT INTO refranero (sentence) VALUES ("Por el canto se conoce el pajaro");
INSERT INTO refranero (sentence) VALUES ("Por el hilo se saca el ovillo");
INSERT INTO refranero (sentence) VALUES ("Por el interes, te quiero Andres");
INSERT INTO refranero (sentence) VALUES ("Por la boca muere el pez");
INSERT INTO refranero (sentence) VALUES ("Por San Blas la cigüena veras");
INSERT INTO refranero (sentence) VALUES ("Por sus frutos los conocereis");
INSERT INTO refranero (sentence) VALUES ("Por un clavo se pierde una herradura");
INSERT INTO refranero (sentence) VALUES ("Por un oido me entra y por otro me sale");
INSERT INTO refranero (sentence) VALUES ("Por un perro que mate, mataperros me llamaron");
INSERT INTO refranero (sentence) VALUES ("Preguntando se va a Roma");
INSERT INTO refranero (sentence) VALUES ("Primero es la obligacion que la devocion");
INSERT INTO refranero (sentence) VALUES ("Que cada palo aguante su vela");
INSERT INTO refranero (sentence) VALUES ("Querer es poder");
INSERT INTO refranero (sentence) VALUES ("Quien a buen arbol se arrima buena sombra le cobija");
INSERT INTO refranero (sentence) VALUES ("Quien a hierro mata, a hierro muere");
INSERT INTO refranero (sentence) VALUES ("Quien bien ata, bien desata");
INSERT INTO refranero (sentence) VALUES ("Quien bien siembra bien recoge");
INSERT INTO refranero (sentence) VALUES ("Quien bien te quiere, te hara llorar");
INSERT INTO refranero (sentence) VALUES ("Quien busca halla");
INSERT INTO refranero (sentence) VALUES ("Quien calla otorga");
INSERT INTO refranero (sentence) VALUES ("Quien con fuego juega se quema");
INSERT INTO refranero (sentence) VALUES ("Quien con lobos anda, a aullar se ensena");
INSERT INTO refranero (sentence) VALUES ("Quien con ninos se acuesta mojado amanece");
INSERT INTO refranero (sentence) VALUES ("Quien da pan a perro ajeno pierde pan y pierde perro");
INSERT INTO refranero (sentence) VALUES ("Quien da primero, da dos veces");
INSERT INTO refranero (sentence) VALUES ("Quien de joven no trabaja de viejo duerme en la paja");
INSERT INTO refranero (sentence) VALUES ("Quien enferma de locura, no tiene cura");
INSERT INTO refranero (sentence) VALUES ("Quien este libre de culpa que tire la primera piedra");
INSERT INTO refranero (sentence) VALUES ("Quien guarda, halla");
INSERT INTO refranero (sentence) VALUES ("Quien hace lo que puede no esta obligado a mas");
INSERT INTO refranero (sentence) VALUES ("Quien hizo la ley hizo la trampa");
INSERT INTO refranero (sentence) VALUES ("Quien llega tarde, ni oye misa ni come carne");
INSERT INTO refranero (sentence) VALUES ("Quien mal anda mal acaba");
INSERT INTO refranero (sentence) VALUES ("Quien mas pone, mas pierde");
INSERT INTO refranero (sentence) VALUES ("Quien mas tiene, mas quiere");
INSERT INTO refranero (sentence) VALUES ("Quien mucho abarca poco aprieta");
INSERT INTO refranero (sentence) VALUES ("Quien mucho duerme, poco aprende");
INSERT INTO refranero (sentence) VALUES ("Quien nace lechon, muere cochino");
INSERT INTO refranero (sentence) VALUES ("Quien no barbecha no cosecha");
INSERT INTO refranero (sentence) VALUES ("Quien no se arriesga, no pasa la mar");
INSERT INTO refranero (sentence) VALUES ("Quien no siembra no recoge");
INSERT INTO refranero (sentence) VALUES ("Quien no te conoce que te compre");
INSERT INTO refranero (sentence) VALUES ("Quien no tenga cabeza, que tenga pies");
INSERT INTO refranero (sentence) VALUES ("Quien no tiene padrino, no se bautiza");
INSERT INTO refranero (sentence) VALUES ("Quien paga descansa");
INSERT INTO refranero (sentence) VALUES ("Quien paga manda");
INSERT INTO refranero (sentence) VALUES ("Quien tiene boca se equivoca");
INSERT INTO refranero (sentence) VALUES ("Quien predica en el desierto pierde el sermon");
INSERT INTO refranero (sentence) VALUES ("Quien roba a un ladron, tiene cien anos de perdon");
INSERT INTO refranero (sentence) VALUES ("Quien se pica ajos come");
INSERT INTO refranero (sentence) VALUES ("Quien siembra vientos recoge tempestades");
INSERT INTO refranero (sentence) VALUES ("Quien tiene un amigo tiene un tesoro");
INSERT INTO refranero (sentence) VALUES ("Quien todo lo quiere, todo lo pierde");
INSERT INTO refranero (sentence) VALUES ("Rectificar es de sabios");
INSERT INTO refranero (sentence) VALUES ("Renovarse o morir");
INSERT INTO refranero (sentence) VALUES ("Reunion de pastores, oveja muerta");
INSERT INTO refranero (sentence) VALUES ("Resulto peor el remedio que la enfermedad");
INSERT INTO refranero (sentence) VALUES ("Salir de Guatemala y entrar en Guatepeor");
INSERT INTO refranero (sentence) VALUES ("Santa Rita, Rita, lo que se da no se quita");
INSERT INTO refranero (sentence) VALUES ("Sarna con gusto no pica");
INSERT INTO refranero (sentence) VALUES ("Se dice el pecado pero no el pecador");
INSERT INTO refranero (sentence) VALUES ("Se dice el pecado pero no el pecador");
INSERT INTO refranero (sentence) VALUES ("Si dices las verdades, pierdes las amistades");
INSERT INTO refranero (sentence) VALUES ("Si hay trato, pueden ser amigos perro y gato");
INSERT INTO refranero (sentence) VALUES ("Si la envidia fuera tina, ¡cuantos tinosos habria!");
INSERT INTO refranero (sentence) VALUES ("Si la montana no va a Mahoma, Mahoma va a la montana");
INSERT INTO refranero (sentence) VALUES ("Si no puedes con tu enemigo, unete a el");
INSERT INTO refranero (sentence) VALUES ("Si no quieres una taza, taza y media");
INSERT INTO refranero (sentence) VALUES ("Si no te envidia nadie, poco vales");
INSERT INTO refranero (sentence) VALUES ("Si te mandare tu mujer arrojarte de un tajo, ruega a Dios que sea bajo");
INSERT INTO refranero (sentence) VALUES ("Siempre sale a hablar quien tiene por que callar");
INSERT INTO refranero (sentence) VALUES ("Sobre gustos no hay nada escrito");
INSERT INTO refranero (sentence) VALUES ("Tal amo, tal criado");
INSERT INTO refranero (sentence) VALUES ("Tanto tienes, tanto vales");
INSERT INTO refranero (sentence) VALUES ("Tanto va el cantaro a la fuente que al final se rompe");
INSERT INTO refranero (sentence) VALUES ("Tirar la piedra y esconder la mano");
INSERT INTO refranero (sentence) VALUES ("Todo se pega menos la hermosura");
INSERT INTO refranero (sentence) VALUES ("Todo tiene remedio menos la muerte");
INSERT INTO refranero (sentence) VALUES ("Tras cornudo, apaleado");
INSERT INTO refranero (sentence) VALUES ("Tripa vacia, corazon sin alegria");
INSERT INTO refranero (sentence) VALUES ("Un clavo saca otro clavo");
INSERT INTO refranero (sentence) VALUES ("Un grano no hace granero, pero ayuda al companero");
INSERT INTO refranero (sentence) VALUES ("Una aguja en un pajar, es dificil de encontrar");
INSERT INTO refranero (sentence) VALUES ("Una cosa es predicar y otra dar trigo");
INSERT INTO refranero (sentence) VALUES ("Una imagen vale mas que mil palabras");
INSERT INTO refranero (sentence) VALUES ("Una mano lava a la otra, y ambas la cara");
INSERT INTO refranero (sentence) VALUES ("Una vez te casaras y mil te arrepentiras");
INSERT INTO refranero (sentence) VALUES ("Unos lo siembran, y otros lo siegan");
INSERT INTO refranero (sentence) VALUES ("Unos nacen con estrella y otros estrellados");
INSERT INTO refranero (sentence) VALUES ("Unos por otros, la casa sin barrer");
INSERT INTO refranero (sentence) VALUES ("Unos tanto y otros tan poco");
INSERT INTO refranero (sentence) VALUES ("Unos tienen la fama, y otros cardan la lana");
INSERT INTO refranero (sentence) VALUES ("Uso hace maestro");
INSERT INTO refranero (sentence) VALUES ("Vemos la paja en el ojo ajeno, y no vemos la viga en el nuestro");
INSERT INTO refranero (sentence) VALUES ("Visteme despacio que tengo prisa");
INSERT INTO refranero (sentence) VALUES ("Zapatero, a tus zapatos");
INSERT INTO refranero (sentence) VALUES ("Zurron de mendigo, nunca bien henchido");